version: '3.8'
services:
  order-service:
    image: orderservice:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  payment-service:
    image: paymentservice:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge